languageCode = "en-us"
title = "Mike Perham"
baseURL = "http://www.mikeperham.com"
theme = "simple-hugo"
relativeURLs = true
publishDir = "docs"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]
PygmentsCodeFences = true
rssLimit = 10
disqusShortname = "mikeperham"

[permalinks]
  post = "/:year/:month/:day/:title/"

[params]
  author = "Mike Perham"
  shortDescription = "Ruby, OSS and the Internet"
  email = "mperham@gmail.com"
  github = "mperham"
  twitter = "mperham"

[blackfriday]
smartypants = false

[params.links]

[params.links.aSidekiq]
"url" = "http://sidekiq.org/"
"title" = "Sidekiq"

[params.links.bFaktory]
"url" = "http://contribsys.com/faktory/"
"title" = "Faktory"

[params.links.cAbout]
"url" = "/about/"
"title" = "About"
