languageCode = "en-us"
title = "Mike Perham"
baseURL = "http://www.mikeperham.com/"
theme = "simple-hugo"
relativeURLs = true
enableEmoji = true
publishDir = "docs"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]

[permalinks]
  post = "/:year/:month/:day/:title/"

[author]
    name = "Mike Perham"
    email = "mperham@gmail.com"

[params]
  author = "Mike Perham"
  shortDescription = "Ruby, OSS and the Internet"
  email = "mperham@gmail.com"
  github = "mperham"
  twitter = "mperham"

[blackfriday]
smartypants = false

[params.links]

[params.links.aSidekiq]
"url" = "http://sidekiq.org/"
"title" = "Sidekiq"

[params.links.bInspeqtor]
"url" = "http://contribsys.com/inspeqtor/"
"title" = "Inspeqtor"

[params.links.cEvents]
"url" = "/events/"
"title" = "Events"

[params.links.dAbout]
"url" = "/about/"
"title" = "About"
